ifndef::target-release[]
include::define-literal.adoc[]
endif::[]

[[ASCIIDOC-SYNTAX-DEFINE]]
== 文言や画像、リンク等の定義と利用

Asciidocでは定義済み項目を本文中に直書きすることなく簡単に利用することができます。

define-literal.adocに定義された情報は「\{name-role-sample}」のように記載することで「{name-role-sample}」と出力したり、
定義された画像として「\{icon-sample-user}」のように記載することで「{icon-sample-user}」と出力することができます。

[.accordion.source,asciidoc,linenums]
----
define-literal.adocに定義された情報は「\{name-role-sample}」のように記載することで「{name-role-sample}」と出力したり、
定義された画像として「\{icon-sample-user}」のように記載することで「{icon-sample-user}」と出力することができます。
----


[[ASCIIDOC-SYNTAX-SECTION-LEVEL]]
== セクションタイトルのレベルについて

asciidocはヘッダー(見出し)の扱いが厳格な文書形式です。 +
また多くの人が同時に修正しやすくGitでのマージ等が低コストで行えるように、
レベル2のヘッダーごとにインクルードによるファイルの分割してください。 +
また、分割したファイルでは原則レベル3以降のヘッダーを利用し文書の構造化に努めてください。

[.accordion.source,asciidoc,linenums]
----
[[include]]
= 参照先の章の名称
\include::include.adoc[]
----

インクルードするファイルのレベルは「leveloffset」を利用して以下の記載をすると揃えることができます。

[.accordion.source,asciidoc,linenums]
----
\include::include.adoc[leveloffset=+2]
----


== 出力設定について

AsciiDocではifdef(ifndef)ディレクティブを利用した簡易的な出力制御が可能です。 +
本ドキュメントでは主に以下の定義を利用して状況や対象者によって以下のように出力を切り替えています。

[.accordion.source,asciidoc,linenums]
----
\ifdef::backend-html5[]
HTMLのみの出力内容
\endif::[]

\ifndef::backend-pdf[]
PDFでは出力されない内容
\endif::[]

\ifndef::target-readme[]
自動化した出力では利用しない内容
(「target-readme」は本サンプルで定義している項目)
\endif::[]

\ifdef::target-sample[]
明示的にendifを記載する場合。
(「target-sample」は本サンプルで定義している項目)
\endif::target-sample[]
----

その他、本ナレッジで定義している項目の詳細は「<<README-GITHUB-WORKFLOWS-TARGET>>」を参照してください。

[[ASCIIDOC-SYNTAX-IMAGES]]
== 画像について

ここでは利用方法を記載します。 +
作成方法は各画像の格納先「<<IMAGE-MANAGEMENT>>」を参照してください。

[[ASCIIDOC-SYNTAX-IMAGE-BLOCK]]
=== ブロックでの記述

.ブロック画像
image::images/Logo/analog-logo.svg[pageTop,{full-page}]

[.accordion.source]
----
.ブロック画像
image::images/Logo/analog-logo.svg[Logo,{half-size}]
----

画像の指定には定義を利用したサイズルールがあります。 +
定義を利用することで、全てのサイズを統一することが可能です。

[.accordion]
====
.サイズの記載
[%header,cols="2,2,3"]
|===
|対象 |定義 | 備考
|外部ドキュメントの貼り付け |full-width | センタリングも行います。
|サムネイル |thumbnail |
|フルサイズの画面幅 |full-page |
|ダイアログのみの画像 |dialog-page |
|===
====

[[ASCIIDOC-SYNTAX-IMAGE-INLINE]]
=== インラインでの記述

インライン {icon-h-write} で表示
image:images/SvgBadges/badges/badge-user-analog-check.svg[]

[.accordion.source,asciidoc,linenums]
----
インライン {icon-h-write} で表示
image:images/SvgBadges/badges/badge-user-analog-check.svg[]
----


== 表の書き方

普段の利用でMarkdownより大きな利便性を感じる場面は表の扱いです。 +
ここでは本ドキュメントで利用している記載法を紹介します。


.複雑な表の扱い
[%header,cols="1,2,3"]
|===
|TH サイズ1 |TH サイズ2 |TH サイズ3

<|<で左寄せ R1C1
^|^で中央寄せ R1C2
>|>で右寄せ R1C3

h|hで個別のヘッダ
|AsciiDoc記法で改行→
|セル内で +
改行

|TD
|AsciiDoc記法のリスト→
<a|
* [.cellsfont]#<で左寄せを明示#
* [.cellsfont]#aでAsciiDoc記法を許容#
* [.cellsfont]#[.cellsfont]#内容#にてフォントをテーブルと合わせる#

.3+|.n+縦に結合 +
| {set:cellbgcolor:#00ccff} TD +
色の指定
| {set:cellbgcolor:#transparent} TD +
色の指定(継承)

2+|n+横に結合

| {set:cellbgcolor:#00ccff} TD +
色の指定
| ↑ 結合されたカラムの定義はしません +
色の指定は連続する

3+a| {set:cellbgcolor:#transparent}

[.cellsfont]#結合時など色の指定の影響(継承の扱いは微妙)#

[.cellsfont]#aで内部にテーブル#
[%header,cols="1,3"]
!===
![.cellsfont]#no.# ![.cellsfont]#内容#
^![.cellsfont]#1#
![.cellsfont]#ただしセパレータを\!にかえる#
!===
// 隙間が足りない事があるので隠し文字をいれる
{zwsp}
|===
//最終セルのカラーをリセットして他のテーブルに影響しない様にする
{set:cellbgcolor!}

[.accordion.source,asciidoc,linenums]
----
.複雑な表の扱い
[%header,cols="1,2,3"]
|===
|TH サイズ1 |TH サイズ2 |TH サイズ3

<|<で左寄せ R1C1
^|^で中央寄せ R1C2
>|>で右寄せ R1C3

h|hで個別のヘッダ
|AsciiDoc記法で改行→
|セル内で +
改行

|TD
|AsciiDoc記法のリスト→
<a|
* [.cellsfont]#<で左寄せを明示#
* [.cellsfont]#aでAsciiDoc記法を許容#
* [.cellsfont]#[.cellsfont]#内容#にてフォントをテーブルと合わせる#

.3+|.n+縦に結合 +
| {set:cellbgcolor:#00ccff} TD +
色の指定
| {set:cellbgcolor:#transparent} TD +
色の指定(継承)

2+|n+横に結合

| {set:cellbgcolor:#00ccff} TD +
色の指定
| ↑ 結合されたカラムの定義はしません +
色の指定は連続する

3+a| {set:cellbgcolor:#transparent}

[.cellsfont]#結合時など色の指定の影響(継承の扱いは微妙)#

[.cellsfont]#aで内部にテーブル#
[%header,cols="1,3"]
!===
![.cellsfont]#no.# ![.cellsfont]#内容#
^![.cellsfont]#1#
![.cellsfont]#ただしセパレータを\!にかえる#
!===
// 隙間が足りない事があるので隠し文字をいれる
{zwsp}
|===
//最終セルのカラーをリセットして他のテーブルに影響しない様にする
{set:cellbgcolor!}
----

== ロール指定による文字のスタイル指定

以下のようにロールを利用してスタイルを適用できます。

* 指定なし
* *強調によるボールド*
* [.big]#大きめ文字#
* [.red]#赤#
* [.orange.big]#オレンジ大きめ文字#
* [.navy.big]#*青の大きめ文字ボールド*#
* [.cellsfont]#テーブル内と同じ文字#
* [.cellsfont.red]#テーブル内の赤字#

[.accordion.source,asciidoc,linenums]
----
* 指定なし
* *強調によるボールド*
* [.big]#大きめ文字#
* [.red]#赤#
* [.orange.big]#オレンジ大きめ文字#
* [.navy.big]#*青の大きめ文字ボールド*#
* [.cellsfont]#テーブル内と同じ文字#
* [.cellsfont.red]#テーブル内の赤字#
----

== 特殊なAttributeの利用

=== リンクの定義

:link:https://sample.asciidoc.analog-inc.com[サンプルを閲覧できるAzure static web appsサイト]

本ドキュメントは{zwsp}{link-site-preview}で閲覧できます。 +
\{zwsp}は日本語との結合時に必要です。

[.accordion.source,asciidoc,linenums]
----
:link:https://sample.asciidoc.analog-inc.com[サンプルを閲覧できるAzure static web appsサイト]

本ドキュメントは{zwsp}{link-site-preview}で閲覧できます。 +
\{zwsp}は日本語との結合時に必要です。
----

=== 定義の途中で色指定

:name-button-test: 【テスト】ボタン
:name-button-test-red-name: pass:quotes[[.red]#【テスト】#]
:name-button-test-red: {name-button-test-red-name}{zwsp}ボタン

通常の記載は『{name-button-test}』で、一部のみ赤字は『{name-button-test-red}』です。
/{zwsp}がpassでそのまま出力されるために2行に分けています。

[.accordion.source,asciidoc,linenums]
----
:name-button-test: 【テスト】ボタン
:name-button-test-red-name: pass:quotes[[.red]#【テスト】#]
:name-button-test-red: {name-button-test-red-name}{zwsp}ボタン

通常の記載は『{name-button-test}』で、一部のみ赤字は『{name-button-test-red}』です。
/{zwsp}がpassでそのまま出力されるために2行に分けています。
----

=== 定義内で改行

:sentence-no-newline: 定義内で改行はしても \
表示では改行しません。

:sentence-newline: 定義内で改行して + \
表示でも改行します。

{sentence-no-newline} +
{sentence-newline}

[.accordion.source,asciidoc,linenums]
----
:sentence-no-newline: 定義内で改行はしても \
表示では改行しません。

:sentence-newline: 定義内で改行して + \
表示でも改行します。

{sentence-no-newline} +
{sentence-newline}
----

== 脚注

脚注はアイコンが左側に表示されるスタイルです。
変更容易性や表現の幅を考慮しブロック形式で記載することをお勧めします。

[NOTE]
.[.navy.big]#*NOTE*#
====
インフォメーションマークが出力されます。 +
補足となる内容や追加の情報が必要な場合に記載してください。
====

[.accordion.source,asciidoc,linenums]
----
[NOTE]
.[.navy.big]#*NOTE*#
====
インフォメーションマークが出力されます。 +
補足となる内容を記載してください。
====
----

[TIP]
.[.big]#*TIP*#
====
電球マークが出力されます。 +
少し高度な利用方法などを記載してください。 +
ユーザーが行う解決策などを提示する場合に利用してください。
====

[.accordion.source,asciidoc,linenums]
----
[TIP]
.[.big]#*TIP*#
====
電球マークが出力されます。 +
少し高度な利用方法などを記載してください。
====
----

[WARNING]
.[.orange.big]#*WARNING*#
====
三角オレンジの注意マークが出力されます +
システムを利用する上で不用意にデータの閲覧ができなくなるなどの +
問題を回避する方法を記載してください。
====

[.accordion.source,asciidoc,linenums]
----
[WARNING]
.[.orange.big]#*WARNING*#
====
三角オレンジの注意マークが出力されます +
システムを利用する上で不用意にデータの閲覧ができなくなるなどの +
問題を回避する方法を記載してください。
====
----

[IMPORTANT]
.[.red.big]#*IMPORTANT*#
====
丸い赤の警告マークが出力されます +
システムを利用する上でセキュリティリスクなどを記載してください。
====

[.accordion.source,asciidoc,linenums]
----
[IMPORTANT]
.[.red.big]#*IMPORTANT*#
====
丸い赤の警告マークが出力されます +
システムを利用する上でセキュリティリスクなどを記載してください。
====
----


[CAUTION]
.[.darkgreen.big]#*CAUTION*#
====
現在ある不具合やバグ、明らかな矛盾点など記載してください。
====


[.accordion.source,asciidoc,linenums]
----
[CAUTION]
.[.darkgreen.big]#*CAUTION*#
====
現在ある不具合やバグ、明らかな矛盾点など記載してください。
====

----

== ブロック

=== Example block (例示)

.〇〇について
[example]
====
例示的な内容を指定するか、 +
または勧告ブロックを定義します。

. リスト
. リスト
====

[.accordion.source,asciidoc,linenums]
----
.〇〇について
[example]
====
例示的な内容を指定するか、 +
または勧告ブロックを定義します。

. リスト
. リスト
====
----

=== Listing block

.〇〇について
[listing, javascript]
----
// 入力されたソースコードやキーボード入力が表示されます

ただし +
吹き出し機能が使えます。<!--1-->

document.write("Hello world!!");

----
<1> 吹き出しの内容をここで定義します。

[.accordion.source,asciidoc,linenums]
----
.〇〇について
[listing, javascript]
\----
// 入力されたソースコードやキーボード入力が表示されます

ただし +
吹き出し機能が使えます。<!--1-->

document.write("Hello world!!");

\----
<1> 吹き出しの内容をここで定義します。
----

=== Fenced


.〇〇について
```
// 入力されたソースコードまたはキーボード入力が表示されます。
ドキュメントで有効になっていて、言語が設定されている場合は、 +
ソース・ハイライターで色付けされます。

document.write("Hello world!!");
```


[.accordion.source,asciidoc,linenums]
----
.〇〇について
```
// 入力されたソースコードまたはキーボード入力が表示されます。
ドキュメントで有効になっていて、言語が設定されている場合は、 +
ソース・ハイライターで色付けされます。

document.write("Hello world!!");
```
----

=== Literal block

.〇〇について
[literal]
....
入力された通りに +
出力テキストが表示されます
吹き出し機能が使えます。<!--1-->
....
<1> 吹き出しの内容をここで定義します。

 スペースを開けた一行が同じ表示になるので注意

[.accordion.source,asciidoc,linenums]
----
.〇〇について
[literal]
....
入力された通りに +
出力テキストが表示されます
吹き出し機能が使えます。<!--1-->
....
<1> 吹き出しの内容をここで定義します。

 スペースを開けた一行が同じ表示になるので注意
----

=== Passthrough block

.〇〇について
[pass]
++++
出力に直接送られる +
未処理のコンテンツ
++++

[.accordion.source,asciidoc,linenums]
----
.〇〇について
[pass]
++++
出力に直接送られる +
未処理のコンテンツ
++++
----

=== Blockquotes(引用)

.〇〇について
[quote, Albert Einstein,proverb,]
----
ミスをしたことのない人は、 +
新しいことに挑戦したことがありません。
吹き出し機能が使えます。<!--1-->
----
<1> 吹き出しの内容をここで定義します。

[.accordion.source,asciidoc,linenums]
----
.〇〇について
[quote, Albert Einstein,proverb,]
\----
ミスをしたことのない人は、 +
新しいことに挑戦したことがありません。
吹き出し機能が使えます。<!--1-->
\----
<1> 吹き出しの内容をここで定義します。
----

=== Sidebar

.〇〇について
[sidebar]
****
文書の流れの外に表示される +
テキストやコンテンツを
非表示にする

. リスト
. リスト
****

[.accordion.source,asciidoc,linenums]
----
.〇〇について
[sidebar]
****
文書の流れの外に表示される +
テキストやコンテンツを
非表示にする

. リスト
. リスト
****
----

=== Source

.〇〇について
[source,javascript]
----
// 入力されたとおりに表示されるソースコードまたはキーボード入力。
ドキュメントで有効になっていて、言語が設定されている場合は、 +
ソース・ハイライターで色付けされます。
吹き出し機能が使えます。<!--1-->

document.write("Hello world!!");

----
<1> 吹き出しの内容をここで定義します。

[.accordion.source,asciidoc,linenums]
----
.〇〇について
[source,Java]
/----
// 入力されたとおりに表示されるソースコードまたはキーボード入力。
ドキュメントで有効になっていて、言語が設定されている場合は、 +
ソース・ハイライターで色付けされます。
吹き出し機能が使えます。<!--1-->

document.write("Hello world!!");

/----
<1> 吹き出しの内容をここで定義します。
----

=== Stem

.〇〇について
[stem]
++++
インタプリタに直接送られる未処理のコンテンツ (AsciiMath や LaTeX math など)
++++

[.accordion.source,asciidoc,linenums]
----
.〇〇について
[stem]
++++
インタプリタに直接送られる未処理のコンテンツ (AsciiMath や LaTeX math など)
++++
----

== リスト

=== 順序無しリストのネスト

* レベル１
** レベル２
*** レベル３
** レベル２

[.accordion.source,asciidoc,linenums]
----
* レベル１
** レベル２
*** レベル３
** レベル２
----

=== 順序ありリストのネスト

. 手順１
. 手順２
.. 手順２a
.. 手順２b
. 手順３

[.accordion.source,asciidoc,linenums]
----
. 手順１
. 手順２
.. 手順２a
.. 手順２b
. 手順３
----

=== チェックリスト

リーフレットなどを作成する場合に利用してください。

- [*] チェック済みの要素
- [x] これもチェック済みの要素
- [ ] 未チェックの要素

[.accordion.source,asciidoc,linenums]
----
- [*] チェック済みの要素
- [x] これもチェック済みの要素
- [ ] 未チェックの要素
----


== カウンター

{counter2:sequence-count-sample-no:0}カウンターは型を定義することができる。 +
{counter:sequence-count-sample-no}.{nbsp}カウンターの利用方法 +
{counter:sequence-count-sample-no}.{nbsp}自動的にインクリメント +
{counter2:sequence-count-sample-no}見せずにインクリメント +
{counter:sequence-count-sample-no}.{nbsp}飛んでるはず

:sequence-count-sample-no: 0

{counter:sequence-count-sample-no}.{nbsp}リセットは普通のAttributeと同じ

{counter:sequence-count-sample-alphabet:a}.{nbsp}カウンターは型を定義することができる。 +
{counter:sequence-count-sample-alphabet}.{nbsp}インクリメントができればいい

[.accordion.source,asciidoc,linenums]
----
{counter2:sequence-count-sample-no:0}カウンターは型を定義することができる。 +
{counter:sequence-count-sample-no}.{nbsp}カウンターの利用方法 +
{counter:sequence-count-sample-no}.{nbsp}自動的にインクリメント +
{counter2:sequence-count-sample-no}見せずにインクリメント +
{counter:sequence-count-sample-no}.{nbsp}飛んでるはず

:sequence-count-sample-no: 0

{counter:sequence-count-sample-no}.{nbsp}リセットは普通Attributeと同じ

{counter:sequence-count-sample-alphabet:a}.{nbsp}カウンターは型を定義することができる。 +
{counter:sequence-count-sample-alphabet}.{nbsp}インクリメントができればいい

----


== 改ページ
----
<<<
----


== コメントアウト

=== インライン

//はコメントアウトになり出力されません。
----
//はコメントアウトになり出力されません。
----


=== ブロック

////
ここにコメント
////

----
////
ここにコメント
////
----

== ラベル

辞書形式に利用します。

第一項:: 第一項の定義
二条::: 第一項二条の定義
第二項:: 第二項の定義

[.accordion.source,asciidoc,linenums]
----
第一項:: 第一項の定義
第一項二条::: 第一項二条の定義
第二項:: 第二項の定義
----


== 水平罫線

水平罫線は以下のように記載します。

'''

[.accordion.source,asciidoc,linenums]
----
'''
----

== インラインマクロ

=== Inline image macro

「image:」で始まるインライン画像はインラインマクロの一つです。 +
詳しくは「<<ASCIIDOC-SYNTAX-IMAGE-INLINE>>」を参照してください。

=== Inline pass macro

「pass:」を利用するとAsciiDocの文法などが無視され未処理でそのまま出力されます。

=== Inline Macro Processor Extension

Inline Macro Processor Extensionは自分で処理を記載して利用するAsciidoctor Extensionsの1種類です。

// Inline Macro Processor Extensionの詳細はサンプルを配置してください。

==== datetimeformat

include::lib/datetimeformat-InlineMacroProcessor/sample.adoc[leveloffset=+4]


== 記号の記載

一部の記号は記載時にリプレースやエスケープを行う必要があります。

例えば「{vbar}」はリプレースとして「\{vbar}」と記載を行います。
また、テーブル内で別のセパレーターとして「!」と利用する場合などはエスケープとして「/!」とすることで出力できます。

[.accordion.source,asciidoc,linenums]
----
例えば「{vbar}」はリプレースとして「\{vbar}」と記載を行います。
また、テーブル内で別のセパレーターとして「!」と利用する場合などはエスケープとして「/!」とすることで出力できます。
----

以下はリプレースを行うべき記号や文字のリストとなります。

[.accordion]
.リプレース対象の定義済み文字 ^[1][2][3]^
====
[width="75%", cols="^4m,^3l,^3"]
|===
|Attribute name |Replacement text |Appearance

|blank
e|nothing
|{empty}

|empty
e|nothing
|{empty}

|sp
e|single space
|{sp}

|nbsp
|&#160;
|{nbsp}

|zwsp^[4]^
|&#8203;
|{zwsp}

|wj^[5]^
|&#8288;
|{wj}

|apos
|&#39;
|{apos}

|quot
|&#34;
|{quot}

|lsquo
|&#8216;
|{lsquo}

|rsquo
|&#8217;
|{rsquo}

|ldquo
|&#8220;
|{ldquo}

|rdquo
|&#8221;
|{rdquo}

|deg
|&#176;
|{deg}

|plus
|&#43;
|{plus}

|brvbar
|&#166;
|&#166;

|vbar
|\|
|{vbar}

|amp
|&
|&

|lt
|<
|<

|gt
|>
|>

|startsb
|[
|[

|endsb
|]
|]

|caret
|^
|^

|asterisk
|*
|*

|tilde
|~
|~

|backslash
|\
|\

|backtick
|`
|`

|two-colons
|::
|::

|two-semicolons
|;;
|;;

|cpp
|C++
|C++
|===


^[1]^ いくつかの置換はUnicode文字ですが、他の置換は数値の文字参照です(例えば、\&#34;)。
これらの文字参照は、Unicode文字の使用がAsciiDocの構文に干渉したり、レンダラー(すなわちブラウザ)を混乱させる可能性がある場合に使用されます。
参照をレンダラーが理解できるものに変換するのはコンバータ次第です(マニュアルページとPDFコンバータの両方が処理するもの)。

^[2]^ Asciidoctor は、定義済みの属性を再割り当てすることを妨げるものではありません。
しかし、出力形式が異なるエンコーディング方式の使用を必要としない限り、それらを読み取り専用として扱うのが最善です。
これらの属性は、コンテンツとプレゼンテーションを切り離すための効果的なツールです。

^[3]^ Asciidoctorでは、HTMLで定義されている名前付き文字参照(別名：名前付き実体)のいずれかを使用できます。
しかし、名前付き文字参照を使用すると、PDFなどの非HTML出力を生成する際に問題が発生することがあります。
これらの名前を解決するために必要な参照テーブルが定義されていない可能性があるからです。私たちの推奨事項は、XMLで定義されているもの(すなわち lt ・ gt ・ amp ・ quot ・ apos)を除いて、名前付き文字参照の使用を避けることです。
その代わりに、数値の文字参照を使用してください。

^[4]^ ゼロ幅空間(ZWSP)は、必要に応じて長い単語を分割できる場所を示すUnicodeのコードポイントです。

^[5]^ ワードジョイナー(WJ)は、その位置での改行を防ぐUnicodeのコードポイントです。
====

== ダイアグラム
Asciidoctorではダイアグラムを記載できますが、生成画像はプレビューできません。 +
ダイアグラムの名称は必ず一意のものを設定してください。


=== ditaaで記述するダイアグラム

[.accordion]
====

[ditaa, asciidoc-syntax-diagram-ditaa-sample, svg]
....
                   +-------------+
                   | Asciidoctor |-------+
                   |   diagram   |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        | --+ Asciidoctor +--> |               |
 |  Text  |   +-------------+    |   Beautiful   |
 |Document|   |   !magic!   |    |    Output     |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
....



[ditaa, asciidoc-syntax-diagram-ditaa-sample-format, svg]
....

          +-----+
          |{d}  |
          |     |
          |     |
          +-----+

          +-----+
          |{s}  |
          |     |
          |     |
          +-----+

          +-----+
          |{io} |
          |     |
          |     |
          +-----+

          Color codes
      /----------+----------\
      |cRED 赤    |cBLU 青    |
      +----------+----------+
      |cGRE 緑    |cPNK ピンク  |
      +----------+----------+
      |cBLK 黒    |cYEL 黄色   |
      \----------+----------/

      /-----------------\
      | Things to do    |
      | cGRE            |
      | o Cut the grass |
      | o Buy jam       |
      | o Fix car       |
      | o Make website  |
      \-----------------/

....

====


=== PlantUMLで記述するダイアグラム

UMLを記述する場合はPlantUMLがおすすめ。 +
多彩なUMLを気軽に記述できる。

[.accordion]
====

[plantuml, asciidoc-syntax-diagram-plantuml-classes, svg]
....
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
....

[plantuml, asciidoc-syntax-diagram-plantuml-sequence, svg]
....
actor Bob #red
' The only difference between actor
'and participant is the drawing
participant Alice
participant "I have a really\nlong name" as L #99FF99
/' You can also declare:
   participant L as "I have a really\nlong name"  #99FF99
  '/

Alice->Bob: Authentication Request
Bob->Alice: Authentication Response
note over Alice, Bob #FFAAAA: This is displayed\n over Bob and Alice.
note over Alice: ノートだよ
Bob->L: Log transaction
Alice->Alice: This is a signal to self.\nIt also demonstrates\nmultiline \ntext
....

====
