// ドキュメント仕様
:asciidoctor:
:doctype: book
:lang: ja
:icons: font
:encoding: utf-8
:backend: html5
:docinfo: shared
// 画像を埋め込み
// :data-uri:
// セクションにアンカーを作成
:sectanchors:
// セクションにリンクを作成
:sectlinks:
// 章番号を付けるか。属性を定義しておくだけで章番号が付けられる。
:sectnums:
// セクションのナンバリングレベルを設定
:sectnumlevels: 6
// ソースコードをハイライトする。
:source-highlighter: coderay
:target-sample:

ifndef::target-release[]
include::define-literal.adoc[]
endif::[]


= 本ドキュメント記載のルール

== 統一した文言と正しい定義について

define-literal.adocに定義ずみの項目については、本文中に直書きすることなく定義を参照して利用するようお願いします。

define-literal.adocに定義された情報は「\{name-role-sample}」のように記載することで「{name-role-sample}」と出力したり、
定義された画像として「\{icon-sample-user}」のように記載することで「{icon-sample-user}」と出力することができます。


[.accordion.source]
----
define-literal.adocに定義された情報は「\{name-role-sample}」のように記載することで「{name-role-sample}」と出力したり、
定義された画像として「\{icon-sample-user}」のように記載することで「{icon-sample-user}」と出力することができます。
----

[IMPORTANT]
.[.red.big]#*用語定義のお願い*#
====
過去の例では表現ゆれの修正に数週間かかるなど、マニュアルのリリースに対して大きなコストがかかることがありました。 +
AscciDocの便利な機能を利用してコスト削減と品質の向上への協力をお願いします。
====

== セクションタイトルのレベルについて

asciidocはヘッダー(見出し)の扱いが厳格な文書形式です。 +
また多くの人が同時に修正しやすくGitでのマージ等が低コストで行えるように、
レベル2のヘッダーごとにインクルードによるファイルの分割を行ってください。 +
また、分割したファイルでは原則レベル3以降のヘッダーを利用し文書の構造化に努めてください。

[.accordion.source]
----
[[include]]
=== 参照先の章の名称
\include::include.adoc[]
----

インクルードするファイルのレベルは「leveloffset」を利用して以下の記載をすると揃えることができます。

[.accordion.source]
----
\include::include.adoc[leveloffset=+2]
----

== 出力設定について

AsciiDocではifdefディレクティブを利用した簡易的な出力制御が可能です。 +
本ドキュメントでは主に以下の定義を利用して状況や対象者によって以下のように出力を切り替えています。

[.accordion.source]
----
\ifdef::backend-html5[]
出力内容
\endif::[]
----

出力フォーマットによる定義::
本項目は出力対象のフォーマットによって異なる値を利用する場合に利用しています。 +
本項目はAsciidocterにて定義されている項目となります。
backend-html5:::
HTML出力時に有効になります。
backend-pdf:::
PDF出力時に有効になります。
プレビューとビルドを分離する定義::
本項目はドキュメント記載時のプレビューと実際のコンバート処理を分離する場合に利用しています。 +
主に、定義を記載したインクルードをかくファイルで行うかの判定に利用しています。 +
本項目は独自定義項目です。
target-release:::
自動での出力時に有効になります。「.github/workflows/asciidoc.sh」内で指定されます。
権限に関する定義::
本項目は各ユーザーに適した内容を出力するために利用しています。 +
自動での出力時に有効になります。「.github/workflows/asciidoc.sh」内で指定されます。 +
本項目は独自定義項目です。
target-sample:::
{name-role-h}向けの出力を行うときに利用します。 +
「.github/workflows/asciidoc.sh」内で出力ファイル毎に指定されます。
target-analog:::
{name-role-p}向けの出力を行うときに利用します。 +
「.github/workflows/asciidoc.sh」内で出力ファイル毎に指定されます。


== 画像について

画像はその対象やフォーマット毎のルールや、利用時のルールがあります。

=== 作成方法

作成方法は各画像の格納先を参照してください。
ifdef::target-release[]
(参照 : <<IMAGE-MANAGEMENT>>)
endif::[]


=== 記述方法

==== ブロック

.ブロック画像
image::images/Logo/analog-logo.svg[pageTop,{full-page}]

[.accordion.source]
----
.ブロック画像
image::images/Logo/analog-logo.svg[Logo,{half-size}]
----

画像の指定には定義を利用したサイズルールがあります。 +
定義を利用することで、全てのサイズを統一することが可能です。

[.accordion]
====
.サイズの記載
[%header,cols="2,2,3"]
|===
|対象 |定義 | 備考
|外部ドキュメントの貼り付け |full-width | センタリングも行います。
|サムネイル |thumbnail |
|フルサイズの画面幅 |full-page |
|ダイアログのみの画像 |dialog-page |
|===
====

==== インライン

インライン {icon-analog-write} で表示

[.accordion.source]
----
インライン {icon-analog-write} で表示
----

ifdef::backend-html5[]
==== VIDEO
ビデオも利用できますが、PDFに埋め込むことはできません。 +
また、ビデオはHTMLファイル中にファイルを埋め込むことができないため1HTMLファイルでの提供はできなくなります。

.ビデオサンプル
video::images/video/sample.mp4[Video,{half-width}]

[.accordion.source]
----
.ビデオサンプル
video::images/video/sample.mp4[Video,{half-width}]
----

endif::[]

== AsciiDoc記述方法と本ドキュメント推奨の記載方法

=== 表の書き方

普段の利用でMarkdownより大きな利便性を感じる場面は表の扱いです。 +
ここでは本ドキュメントで利用している記載法を紹介します。


.複雑な表の扱い
[%header,cols="1,2,3"]
|===
|TH サイズ1 |TH サイズ2 |TH サイズ3

<|<で左寄せ R1C1
^|^で中央寄せ R1C2
>|>で右寄せ R1C3

h|hで個別のヘッダ
|AsciiDoc記法で改行→
|セル内で +
改行

|TD
|AsciiDoc記法のリスト→
<a|
* [.cellsfont]#<で左寄せを明示#
* [.cellsfont]#aでAsciiDoc記法を許容#
* [.cellsfont]#[.cellsfont]#内容#にてフォントをテーブルと合わせる#

.3+|.n+縦に結合 +
|TD
|TD

2+|n+横に結合

|TD
|結合されたカラムの定義はしません

3+a|
[.cellsfont]#aで内部にテーブル#
[%header,cols="1,3"]
!===
![.cellsfont]#no.# ![.cellsfont]#内容#
^![.cellsfont]#1#
![.cellsfont]#ただしセパレータを\!にかえる#
!===
// 隙間が足りない事があるので隠し文字をいれる
{zwsp}
|===

[.accordion.source]
----
.複雑な表の扱い
[%header,cols="1,2,3"]
|===
|TH サイズ1 |TH サイズ2 |TH サイズ3

<|<で左寄せ R1C1
^|^で中央寄せ R1C2
>|>で右寄せ R1C3

h|hで個別のヘッダ
|AsciiDoc記法で改行→
|セル内で +
改行

|TD
|AsciiDoc記法のリスト→
<a|
* [.cellsfont]#<で左寄せを明示#
* [.cellsfont]#aでAsciiDoc記法を許容#
* [.cellsfont]#[.cellsfont]#内容#にてフォントをテーブルと合わせる#

.3+|.n+縦に結合 +
|TD
|TD

2+|n+横に結合

|TD
|結合されたカラムの定義はしません

3+a|
[.cellsfont]#aで内部にテーブル#
[%header,cols="1,3"]
!===
![.cellsfont]#no.# ![.cellsfont]#内容#
^![.cellsfont]#1#
![.cellsfont]#ただしセパレータを\!にかえる#
!===
// 隙間が足りない事があるので隠し文字をいれる
{zwsp}
|===
----

.外部CSVファイルを利用したテーブル
[format="csv", options="header,footer" cols=",,"]
|===
include::table.csv[]
|===

[.accordion.source]
----
.外部CSVファイルを利用したテーブル
[format="csv", options="header,footer" cols=",,"]
|===
\include::table.csv[]
|===
----
=== ロール指定による文字のスタイル指定

以下のようにロールを利用してスタイルを適用することができます。

* 指定なし
* *強調によるボールド*
* [.big]#大きめ文字#
* [.red]#赤#
* [.orange.big]#オレンジ大きめ文字#
* [.navy.big]#*青の大きめ文字ボールド*#
* [.cellsfont]#テーブル内と同じ文字#
* [.cellsfont.red]#テーブル内の赤字#

[.accordion.source]
----
* 指定なし
* *強調によるボールド*
* [.big]#大きめ文字#
* [.red]#赤#
* [.orange.big]#オレンジ大きめ文字#
* [.navy.big]#*青の大きめ文字ボールド*#
* [.cellsfont]#テーブル内と同じ文字#
* [.cellsfont.red]#テーブル内の赤字#
----

=== 特殊なAttributeの利用

==== リンクの定義

:link-site-preview: https://ashy-coast-0be90a600.azurestaticapps.net[リリース作業中マニュアルが閲覧できるAzure static web appsサイト]

本ドキュメントは{zwsp}{link-site-preview}で閲覧できます。 +
\{zwsp}は日本語との結合時に必要です。

[.accordion.source]
----
:link-site-preview: https://ashy-coast-0be90a600.azurestaticapps.net[リリース作業中マニュアルが閲覧できるAzure static web appsサイト]

本ドキュメントは{zwsp}{link-site-preview}で閲覧できます。 +
\{zwsp}は日本語との結合時に必要です。
----

==== 定義の途中で色指定

:name-button-test: 【テスト】ボタン
:name-button-test-red-name: pass:quotes[[.red]#【テスト】#]
:name-button-test-red: {name-button-test-red-name}{zwsp}ボタン

通常の記載は『{name-button-test}』で、一部のみ赤字は『{name-button-test-red}』です。
/{zwsp}がpassでそのまま出力されるために2行に分けています。

[.accordion.source]
----
:name-button-test: 【テスト】ボタン
:name-button-test-red-name: pass:quotes[[.red]#【テスト】#]
:name-button-test-red: {name-button-test-red-name}{zwsp}ボタン

通常の記載は『{name-button-test}』で、一部のみ赤字は『{name-button-test-red}』です。
/{zwsp}がpassでそのまま出力されるために2行に分けています。
----

==== 定義内で改行

:sentence-no-newline: 定義内で改行はしても \
表示では改行しません。

:sentence-newline: 定義内で改行して + \
表示でも改行します。

{sentence-no-newline} +
{sentence-newline}

[.accordion.source]
----
:sentence-no-newline: 定義内で改行はしても \
表示では改行しません。

:sentence-newline: 定義内で改行して + \
表示でも改行します。

{sentence-no-newline} +
{sentence-newline}
----

=== 注釈等

注釈はアイコンが左側に表示されるスタイルです。
変更容易性や表現の幅を考慮しブロック形式で記載することをお勧めします。

[NOTE]
.[.navy.big]#*NOTE*#
====
インフォメーションマークが出力されます。 +
補足となる内容や追加の情報が必要な場合に記載してください。
====

[.accordion.source]
----
[NOTE]
.[.navy.big]#*NOTE*#
====
インフォメーションマークが出力されます。 +
補足となる内容を記載してください。
====
----

[TIP]
.[.big]#*TIP*#
====
電球マークが出力されます。 +
少し高度な利用方法などを記載してください。 +
ユーザーが行う解決策などを提示する場合に利用してください。
====

[.accordion.source]
----
[TIP]
.[.big]#*TIP*#
====
電球マークが出力されます。 +
少し高度な利用方法などを記載してください。
====
----

[WARNING]
.[.orange.big]#*WARNING*#
====
三角オレンジの注意マークが出力されます +
システムを利用する上で不用意にデータの閲覧ができなくなるなどの +
問題を回避する方法を記載してください。
====

[.accordion.source]
----
[WARNING]
.[.orange.big]#*WARNING*#
====
三角オレンジの注意マークが出力されます +
システムを利用する上で不用意にデータの閲覧ができなくなるなどの +
問題を回避する方法を記載してください。
====
----

[IMPORTANT]
.[.red.big]#*IMPORTANT*#
====
丸い赤の警告マークが出力されます +
システムを利用する上でセキュリティリスクなどを記載してください。
====

[.accordion.source]
----
[IMPORTANT]
.[.red.big]#*IMPORTANT*#
====
丸い赤の警告マークが出力されます +
システムを利用する上でセキュリティリスクなどを記載してください。
====
----

[CAUTION]
.[.crimson.big]#*CAUTION*#
====
現在ある不具合やバグ、明らかな矛盾点など記載してください。
====

[.accordion.source]
----
[CAUTION]
.[.crimson.big]#*CAUTION*#
====
現在ある不具合やバグ、明らかな矛盾点など記載してください。
====
----

=== リスト

==== 順序無しリストのネスト

* レベル１
** レベル２
*** レベル３
** レベル２

[.accordion.source]
----
* レベル１
** レベル２
*** レベル３
** レベル２
----

==== 順序ありリストのネスト

. 手順１
. 手順２
.. 手順２a
.. 手順２b
. 手順３

[.accordion.source]
----
. 手順１
. 手順２
.. 手順２a
.. 手順２b
. 手順３
----

==== チェックリスト

リーフレットなどを作成する場合に利用してください。

- [*] チェック済みの要素
- [x] これもチェック済みの要素
- [ ] 未チェックの要素

[.accordion.source]
----
- [*] チェック済みの要素
- [x] これもチェック済みの要素
- [ ] 未チェックの要素
----


=== カウンター

{counter2:sequence-count-sample-no:0}カウンターは型を定義することができる。 +
{counter:sequence-count-sample-no}.{nbsp}カウンターの利用方法 +
{counter:sequence-count-sample-no}.{nbsp}自動的にインクリメント +
{counter2:sequence-count-sample-no}見せずにインクリメント +
{counter:sequence-count-sample-no}.{nbsp}飛んでるはず

:sequence-count-sample-no: 0

{counter:sequence-count-sample-no}.{nbsp}リセットは普通のAttributeと同じ

{counter:sequence-count-sample-alphabet:a}.{nbsp}カウンターは型を定義することができる。 +
{counter:sequence-count-sample-alphabet}.{nbsp}インクリメントができればいい

[.accordion.source]
----
{counter2:sequence-count-sample-no:0}カウンターは型を定義することができる。 +
{counter:sequence-count-sample-no}.{nbsp}カウンターの利用方法 +
{counter:sequence-count-sample-no}.{nbsp}自動的にインクリメント +
{counter2:sequence-count-sample-no}見せずにインクリメント +
{counter:sequence-count-sample-no}.{nbsp}飛んでるはず

:sequence-count-sample-no: 0

{counter:sequence-count-sample-no}.{nbsp}リセットは普通Attributeと同じ

{counter:sequence-count-sample-alphabet:a}.{nbsp}カウンターは型を定義することができる。 +
{counter:sequence-count-sample-alphabet}.{nbsp}インクリメントができればいい

----


=== 改ページ

==== 改ページ前

<<<

----
<<<
----

==== 改ページ後


=== コメントアウト

==== インライン

//はコメントアウトになり出力されません。
----
//はコメントアウトになり出力されません。
----


==== ブロック

////
ここにコメント
////

----
////
ここにコメント
////
----

=== ラベル

辞書形式に利用します。

第一項:: 第一項の定義
二条::: 第一項二条の定義
第二項:: 第二項の定義

[.accordion.source]
----
第一項:: 第一項の定義
第一項二条::: 第一項二条の定義
第二項:: 第二項の定義
----

=== 水平罫線

水平罫線は以下のように記載します。

'''

[.accordion.source]
----
'''
----

=== 記号の記載

一部の記号は記載時にリプレースやエスケープを行う必要があります。

例えば「{vbar}」はリプレースとして「\{vbar}」と記載を行います。
また、テーブル内で別のセパレーターとして「!」と利用する場合などはエスケープとして「/!」とすることで出力できます。

[.accordion.source]
----
例えば「{vbar}」はリプレースとして「\{vbar}」と記載を行います。
また、テーブル内で別のセパレーターとして「!」と利用する場合などはエスケープとして「/!」とすることで出力できます。
----

以下はリプレースを行うべき記号や文字のリストとなります。

[.accordion]
.リプレース対象の定義済み文字 ^[1][2][3]^
====
[width="75%", cols="^4m,^3l,^3"]
|===
|Attribute name |Replacement text |Appearance

|blank
e|nothing
|{empty}

|empty
e|nothing
|{empty}

|sp
e|single space
|{sp}

|nbsp
|&#160;
|{nbsp}

|zwsp^[4]^
|&#8203;
|{zwsp}

|wj^[5]^
|&#8288;
|{wj}

|apos
|&#39;
|{apos}

|quot
|&#34;
|{quot}

|lsquo
|&#8216;
|{lsquo}

|rsquo
|&#8217;
|{rsquo}

|ldquo
|&#8220;
|{ldquo}

|rdquo
|&#8221;
|{rdquo}

|deg
|&#176;
|{deg}

|plus
|&#43;
|{plus}

|brvbar
|&#166;
|&#166;

|vbar
|\|
|{vbar}

|amp
|&
|&

|lt
|<
|<

|gt
|>
|>

|startsb
|[
|[

|endsb
|]
|]

|caret
|^
|^

|asterisk
|*
|*

|tilde
|~
|~

|backslash
|\
|\

|backtick
|`
|`

|two-colons
|::
|::

|two-semicolons
|;;
|;;

|cpp
|C++
|C++
|===


^[1]^ いくつかの置換はUnicode文字ですが、他の置換は数値の文字参照です(例えば、\&#34;)。
これらの文字参照は、Unicode文字の使用がAsciiDocの構文に干渉したり、レンダラー(すなわちブラウザ)を混乱させる可能性がある場合に使用されます。
参照をレンダラーが理解できるものに変換するのはコンバータ次第です(マニュアルページとPDFコンバータの両方が処理するもの)。

^[2]^ Asciidoctor は、定義済みの属性を再割り当てすることを妨げるものではありません。
しかし、出力形式が異なるエンコーディング方式の使用を必要としない限り、それらを読み取り専用として扱うのが最善です。
これらの属性は、コンテンツとプレゼンテーションを切り離すための効果的なツールです。

^[3]^ Asciidoctorでは、HTMLで定義されている名前付き文字参照(別名：名前付き実体)のいずれかを使用することができます。
しかし、名前付き文字参照を使用すると、PDFなどの非HTML出力を生成する際に問題が発生することがあります。
これらの名前を解決するために必要な参照テーブルが定義されていない可能性があるからです。私たちの推奨事項は、XMLで定義されているもの(すなわち lt ・ gt ・ amp ・ quot ・ apos)を除いて、名前付き文字参照の使用を避けることです。
その代わりに、数値の文字参照を使用してください。

^[4]^ ゼロ幅空間(ZWSP)は、必要に応じて長い単語を分割できる場所を示すUnicodeのコードポイントです。

^[5]^ ワードジョイナー(WJ)は、その位置での改行を防ぐUnicodeのコードポイントです。
====

=== ダイアグラム
Asciidoctorではダイアグラムを記載することができますが、生成画像はプレビューできません。

[.accordion]
==== ditaaで記述するダイアグラム

[ditaa, diagram-sample, svg]
....
                   +-------------+
                   | Asciidoctor |-------+
                   |   diagram   |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        | --+ Asciidoctor +--> |               |
 |  Text  |   +-------------+    |   Beautiful   |
 |Document|   |   !magic!   |    |    Output     |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
....



[ditaa, diagram-format, svg]
....

          +-----+
          |{d}  |
          |     |
          |     |
          +-----+

          +-----+
          |{s}  |
          |     |
          |     |
          +-----+

          +-----+
          |{io} |
          |     |
          |     |
          +-----+

          Color codes
      /----------+----------\
      |cRED 赤    |cBLU 青    |
      +----------+----------+
      |cGRE 緑    |cPNK ピンク  |
      +----------+----------+
      |cBLK 黒    |cYEL 黄色   |
      \----------+----------/

      /-----------------\
      | Things to do    |
      | cGRE            |
      | o Cut the grass |
      | o Buy jam       |
      | o Fix car       |
      | o Make website  |
      \-----------------/

....


[.accordion]
==== PlantUMLで記述するダイアグラム

UMLを記述する場合はPlantUMLがおすすめ。 +
多彩なUMLを気軽に記述できる。



[plantuml, diagram-classes, svg]
....
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
....

[plantuml, diagram-sequence, svg]
....
actor Bob #red
' The only difference between actor
'and participant is the drawing
participant Alice
participant "I have a really\nlong name" as L #99FF99
/' You can also declare:
   participant L as "I have a really\nlong name"  #99FF99
  '/

Alice->Bob: Authentication Request
Bob->Alice: Authentication Response
note over Alice, Bob #FFAAAA: This is displayed\n over Bob and Alice.
note over Alice: ノートだよ
Bob->L: Log transaction
Alice->Alice: This is a signal to self.\nIt also demonstrates\nmultiline \ntext
....



=== 細かな記載ルール


==== システムやその画面上に表現ゆれが存在する場合

基本的には画面上の文言を尊重しますが、それでも表現にゆれがある場合は、
最終的な行為に対する文言を優先してください。

==== 文中のカッコの扱いについて

本画面の参照のうち、表外の項目については【項目名】(選択肢ではない)を利用します。 +
多画面の項目を参照する場合は「項目名」を利用します。

ボタン、画面、ロールなど原則として用語定義を利用するものは「」を利用しません。

==== 「をする場合」など場合を利用する記載について

場合は選択の余地や、ケースによって実施するかしないか異なるフローについて利用します。


==== OR条件AND条件を日本語で記載する場合

===== OR条件

----
[α]または[β]
[A]、[B]、[C]、もしくは[D]等の[α]、または[E]、[F]、[G]、もしくは[H]などの[β]
----
は
----
α or β
α[A or B or C or D (or etc.)] or β[E or F or G or H (or etc.)]
----
となります。

===== AND条件

----
[α]および[β]
[A]、[B]、[C]、および[D]等の[α]、並びに[E]、[F]、[G]、および[H]などの[β]
----
は
----
α and β
α[A and B and C and D (and etc.)] and β[E and F and G and H (and etc.)]
----
となります。

==== 長音記号の有無


===== 主に長音記号を用いるもの

[.accordion]
====
[cols="2,7"]
.主に長音記号を用いるもの
|===
|英単語|カナ
|adapter|アダプター
|administrator|アドミニストレーター
|advisor|アドバイザー
|anchor|アンカー
|behavior|ビヘイビアー
|binder|バインダー
|browser|ブラウザー
|buffer|バッファー
|calendar|カレンダー
|cellular|セルラー
|chapter|チャプター
|condenser|コンデンサー
|constructor|コンストラクター
|consumer|コンシューマー
|container|コンテナー
|controller|コントローラー
|counter|カウンター
|customer|カスタマー
|customizer|カスタマイザー
|cyber|サイバー
|debugger|デバッガー
|decoder|デコーダー
|designer|デザイナー
|developer|デベロッパー
|downloader|ダウンローダー
|driver|ドライバー
|encoder|エンコーダー
|enterprise|エンタープライズ
|error|エラー
|exchanger|エクスチェンジャー
|expander|エキスパンダー
|explorer|エクスプローラー
|extender|エクステンダー
|fiber|ファイバー
|filter|フィルター
|finder|ファインダー
|flow|フロー
|folder|フォルダー
|free|フリー
|gatekeeper|ゲートキーパー
|glow|グロー
|header|ヘッダー
|how-to|ハウツー
|installer|インストーラー
|interceptor|インターセプター
|interpreter|インタープリター
|launcher|ランチャー
|layer|レイヤー
|licensor|ライセンサー
|maker|メーカー
|master|マスター
|member|メンバー
|membership|メンバーシップ
|menu|メニュー
|messenger|メッセンジャー
|meter|メーター
|minor|マイナー
|modular|モジュラー
|monitor|モニター
|number|ナンバー
|officer|オフィサー
|operator|オペレーター
|organizer|オーガナイザー
|owner|オーナー
|parameter|パラメーター
|partner|パートナー
|placeholder|プレースホルダー
|player|プレーヤー
|power|パワー
|presenter|プレゼンター
|printer|プリンター
|protector|プロテクター
|publisher|パブリッシャー
|resolver|リゾルバー
|router|ルーター
|scanner|スキャナー
|selector|セレクター
|seminar|セミナー
|sensor|センサー
|separator|セパレーター
|sequencer|シーケンサー
|serializer|シリアライザー
|server|サーバー
|sidebar|サイドバー
|slow|スロー
|spacer|スペーサー
|splitter|スプリッター
|summary|サマリー
|supervisor|スーパーバイザー
|through|スルー
|toner|トナー
|transfer|トランスファー
|transformer|トランスフォーマー
|translator|トランスレーター
|transponder|トランスポンダー
|tree|ツリー
|trigger|トリガー
|underbar|アンダーバー
|updater|アップデーター
|uploader|アップローダー
|user|ユーザー
|validator|バリデーター
|vector|ベクター
|viewer|ビューアー
|workflow|ワークフロー
|writer|ライター
|===
====

===== 主に長音記号を用い無いもの

[.accordion]
====
[cols="2,7"]
.慣例に基づき変更しないもの
|===
|英単語 | カナ
|accelerator|アクセラレータ
|barrier|バリア
|bazaar|バザール
|bear|ベア
|beer|ビール
|carrier|キャリア
|centimeter|センチメートル
|clear|クリア
|compiler|コンパイラ
|connector|コネクタ
|conveyor|コンベヤ
|dollar|ドル
|door|ドア
|engineer|エンジニア
|exterior|エクステリア
|floor|フロア
|formatter|フォーマッタ
|frontier|フロンティア
|gear|ギア
|humor|ユーモア
|indoor|インドア
|interior|インテリア
|junior|ジュニア
|linear|リニア
|meter|メートル
|millimeter|ミリメートル
|outdoor|アウトドア
|polyester|ポリエステル
|premier|プレミア
|processor|プロセッサ
|programmer|プログラマ
|propeller|プロペラ
|radiator|ラジエータ
|rear|リア
|register|レジスタ
|scheduler|スケジューラ
|security|セキュリティ
|senior|シニア
|slipper|スリッパ
|stellar|ステラ
|terminator|ターミネータ
|transistor|トランジスタ
|volunteer|ボランティア
|===
====

その他の記載については以下を参照のこと

link:https://www.microsoft.com/ja-jp/language/styleguides[Microsoft ローカリゼーション スタイル ガイド +
https://www.microsoft.com/ja-jp/language/styleguides]
