ifndef::target-release[]
include::define-literal.adoc[]
endif::[]


ここでは当リポジトリのディレクトリ構成と含まれるファイルについて説明します。

== ルートディレクトリ

index.adoc:: マニュアル本編としてAsciiDoc最上位のファイルです。実コンテンツをインクルードしている他にも出力に必要な設定を行なっています。
index-download.adoc:: ダウンロードマニュアルとしてAsciiDoc最上位のファイルです。実コンテンツをインクルードしている他にも出力に必要な設定を行なっています。
index-system-administrator.adoc:: システム管理者向けマニュアルとしてAsciiDoc最上位のファイルです。実コンテンツをインクルードしている他にも出力に必要な設定を行なっています。
index-preview.adoc:: Azure static web appsのトップページとなるAsciiDoc最上位のファイルです。実コンテンツをインクルードしている他にも出力に必要な設定を行なっています。
index-version.adoc:: 各ルートファイルのバージョンを一括で設定するときのバージョン保持ファイルです。
README.adoc:: 本章の実体となるファイルです。
descriptionGuidelines.adoc:: 本ドキュメント記載ルールを簡単にまとめたファイルです。
directory-organization.adoc:: 各ディレクトリの構成や内容を記載しています。
define-common.adoc:: index.adocに記載すると盆雑になる出力設定を記載しています。途中の空行を禁止しているファイルです。
define-literal.adoc:: 表現ゆれを防いだり、記載を容易にするための共通的な表現を定義しています。 +
こちらもindex.adocに記載すると盆雑になるため外部定義となっており、編集中のプレビューもできるように、各ファイルの最上部で条件インクルードされています。
define-value-codeNformat.adoc:: 主にソースコードやシステム上の定数値を保持するファイルで、項目一覧などから参照されます。 +
「define-literal.adoc」内の定義を利用するため「define-literal.adoc」下部にインクルードされています。
define-document.adoc:: ドキュメントの名称やリンクを管理します。 +
「define-literal.adoc」内の定義を利用するため「define-literal.adoc」下部にインクルードされています。
define-imageNicon.adoc:: アイコンやイメージの画像を定義しています。
define-preview.adoc:: ローカルプレビュー時の表示モードを定義しています。こちらを書き換えるとローカルでの作業で対象の表示に切り替え可能です。
asciidoc-syntax-reference.adoc:: 当ナレッジを記載するために必要なAsciiDocの記載方法をまとめています。
about-asciidoc.adoc:: AsciiDocやAsciidoctorについてまとめています。
page-\{pagename}.adoc:: 主にページの説明に利用するファイルです。ページ名はリバースドメインを意識して命名しています。
guide-\{guidename}.adoc:: 主にガイド用に利用するファイルです。ガイド名はリバースドメインを意識して命名しています。
section-\{sectionname}.adoc:: 主にセクション(章)用に利用するファイルです。セクション(章)名はリバースドメインを意識して命名しています。
summary-\{summaryname}.adoc:: 主にサマリー(概要やまとめ)用に利用するファイルです。サマリー(概要やまとめ)名はリバースドメインを意識して命名しています。
flow-\{flowname}.adoc:: 主にフロー(操作手順や業務フローなどの流れ)の説明に利用するファイルです。フロー(操作手順や業務フローなどの流れ)名はリバースドメインを意識して命名しています。
file-\{filename}.adoc:: 主にファイル用の説明に利用するファイルです。ファイル名はリバースドメインを意識して命名しています。
file-\{filename}.csv:: 主にファイル用の説明に利用するファイルのうちテーブルの内容のみを取り扱うファイルです。このファイルの編集は直接行わず、同名のエクセル(.xlsx)ファイルから生成します。
file-\{filename}.xlsx:: 同名のCSVファイルを生成するためのファイルです。

== /images ディレクトリ

画像ファイルを配置するディレクトリです。

include::./images/README.adoc[leveloffset=+1]

== /docinfo ディレクトリ

HTML出力用のテーマをとなるHTMLを配置するディレクトリです。

include::./docinfo/README.adoc[leveloffset=+1]

== /themes ディレクトリ

PDF出力用のテーマを配置するディレクトリです。

include::./themes/README.adoc[leveloffset=+1]

[[README-GITHUB-WORKFLOWS]]
== /.github/workflows ディレクトリ

ワークフローの処理を配置するディレクトリです。

include::./.github/workflows/README.adoc[leveloffset=+1]

== /fonts ディレクトリ

PDF出力に必要なフォントファイルを配置するディレクトリです。

include::./fonts/README.adoc[leveloffset=+1]

== /diagram-configs ディレクトリ

一部の標準で回避できない設定を行うファイルを配置するディレクトリです。

include::./diagram-configs/README.adoc[leveloffset=+1]

== /azureFunctions ディレクトリ

Azure static web appsを利用するのに必要なディレクトリです。

include::./azureFunctions/README.adoc[leveloffset=+1]

== /shell-utility ディレクトリ

汎用的なシェルスクリプトを配置するディレクトリです。

include::./shell-utility/README.adoc[leveloffset=+1]

== /lib ディレクトリ

Asciidoctor Extensionsを配置するディレクトリです。

include::./lib/README.adoc[leveloffset=+1]
