本リポジトリは link:https://github.com/Analog-inc/asciidoctor-action[Analog-inc/asciidoctor-action]
を利用するためのサンプルです。 +
本README.adocは本サンプルのindex.adocにインクルードされる想定で記載されています。

=== ドキュメントビルドのステータス

image::https://github.com/Analog-inc/asciidoctor-action-sample/workflows/CI/badge.svg[StatusBatch]
上記バッチは「link:https://github.com/Analog-inc/asciidoctor-action-sample/actions?query=workflow%3ACI[Analog-inc/asciidoctor-action-sample]」で最後にPushした際にアクションの状態を表します。（HTMLでは現在の状態、PDFでは一つ前の状態になります。） +
また、HTML出力ではプライベートリポジトリのステータスはログイン状態でしか取得できません。 +
バッチは以下のフォーマットで表示することが可能です。

  image::https://github.com/{github_id}/{repository}/workflows/{workflow_name}/badge.svg?branch={branch_name}[StatusBatch]

=== 本サンプルの使い方
本サンプルのリポジトリにあるファイルをコピーしご自身のリポジトリに適用していただければ、気軽にAsciiDocを出力することができます。

=== 構成するファイル
AsciiDocを構成するファイルはパスを指定することで、自由に配置できます。 +
ここでは当サンプルに含まれるファイルについて説明します。

==== ルートディレクトリ

index.adoc:: AsciiDocサンプルの最上位のファイルです。実コンテンツをインクルードしている他にも出力に必要な設定を行なっています。
LICENSE.adoc:: ライセンス表記のサンプルです。
README.adoc:: 本章の実体となるファイルでREADMEのサンプルです。
syntax.adoc:: 簡単な記載方法を確認するサンプルです。

==== /.github/workflows ディレクトリ

このディレクトリはワークフローの処理を配置するディレクトリです。

asciidoc.sh:: HTML・PDF・ePubを同時に出力するためのシェルスクリプトです。
asciidoc.yml:: ワークフローを記述したファイルです。

==== /configs ディレクトリ

このディレクトリは一部標準的な設定ではできない設定を行うファイルを配置するディレクトリです。

config.rb:: Rubyでしか設定できない事を記述しています。ダイアグラムに含めるフォントがPDFに埋め込めない問題を解決しています。

==== /fonts ディレクトリ

このディレクトリはフォントファイルを配置するディレクトリです。日本語のファイルはフォントファイルがないとPDF出力できないため配置しています。
このディレクトリには以下のフォントが配置されています。

源真ゴシック:: link:http://jikasei.me/font/genshin/[自家製フォント工房]で配布されているフォントでフリーの OpenType フォントである「源ノ角ゴシック」を TrueType 形式に変換したフォントです。
源様明朝:: link:https://github.com/ButTaiwan/genyo-font/[GitHubのButTaiwan/genyo-font]で配布されているフォントでフリーの OpenType フォントである「源ノ明朝」を TrueType 形式に変換したフォントです。 +
ttcで配布された最新のフォントは句読点の制御が上手く行かないので、少し古いバージョンの物を利用しています。
Noto Emojiフォント:: link:https://www.google.com/get/noto/#emoji-zsye[Google Noto Fontsで提供]されているオープンソースの絵文字フォントです。なお同じ配布元に携帯電話で使えるカラー絵文字もありますがエラーになるため使えません。

==== /images ディレクトリ

このディレクトリは画像ファイルを配置するディレクトリです。このディレクトリの細かい説明は割愛します。

==== /themes ディレクトリ

このディレクトリは出力用のテーマを配置するディレクトリです。

sample-theme.yml:: PDF出力の際に日本語環境に合わせてフォントを指定したり、文書をみやすいフォーマットにするスタイルを記述しています。CSSに似た記述方法になっています。
