ドキュメントの記述方法のサンプルです。

=== 記述方法

本ドキュメントはasciidoc形式で記述します。 +
記載方法の詳細は以下のリンクを参照して記載をお願いします。 +
link:https://takumon.github.io/asciidoc-syntax-quick-reference-japanese-translation/[Asciidoctor 文法クイックリファレンス(日本語訳)]

==== 記述時の注意事項

===== セクションタイトルのレベルについて

asciidocはヘッダー(見出し)の扱いが厳格な文書形式です。 +
また多くの人が同時に修正しやすくGitでのマージ等が低コストで行えるように、
レベル1のヘッダーごとにインクルードによるファイルの分割を行ってください。 +
また、分割したファイルではレベル2以降のヘッダーを利用し文書の構造化に努めてください。

=== 注釈等

NOTE: ノート

TIP: ティップス

IMPORTANT: 重要事項

WARNING: 警告

CAUTION: 注意

=== インクルード

.index.adoc
====
これはindex.adocのサンプルです。
[listing]
....
  = サンプルドキュメント (レベル0)
  [[README]]
  == 本ドキュメントについて (レベル1)
  include::README.adoc[]
....
====


.README.adoc
====
これはREADME.adocのサンプルです。
[listing]
....
  === 方針(レベル2)
  本ドキュメントはAsciidocのビルドサンプルとして利用します。
....
====

=== リスト

順序無しリストのネスト

* レベル１
** レベル２
*** レベル３

==== チェックリスト

- [*] チェック済みの要素
- [x] これもチェック済みの要素
- [ ] 未チェックの要素

=== 改ページ

<<<
==== 改ページ後


=== コメントアウト

==== インライン
//はコメントアウトになり出力されません。

==== ブロック
////
ここにコメント
////

=== ラベル



第一項:: 第一項の定義
第二項:: 第二項の定義

=== 水平罫線

'''

=== 表の書き方

.表の書き方
|===
|カラム名 1 |カラム名 2 |カラム名 3

|カラム 1, 行 1 のセル
|カラム 2, 行 1 のセル
|カラム 3, 行 1 のセル

|カラム 1, 行 2 のセル
|カラム 2, 行 2 のセル
|カラム 3, 行 2 のセル
|===


=== ダイアグラム

==== ditaaで記述するダイアグラム


[ditaa, diagram-sample, png]
....
                   +-------------+
                   | Asciidoctor |-------+
                   |   diagram   |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        | --+ Asciidoctor +--> |               |
 |  Text  |   +-------------+    |   Beautiful   |
 |Document|   |   !magic!   |    |    Output     |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
....

ダイアグラムは文字数カウントなので、気をつけて記載する。 +
また、Asciiアート上のレイアウトがそのまま反映されるので、
センタリング等も気を付ける必要がある。

[ditaa, diagram-format, svg]
....

          +-----+
          |{d}  |
          |     |
          |     |
          +-----+

          +-----+
          |{s}  |
          |     |
          |     |
          +-----+

          +-----+
          |{io} |
          |     |
          |     |
          +-----+

          Color codes
      /----------+----------\
      |cRED 赤    |cBLU 青    |
      +----------+----------+
      |cGRE 緑    |cPNK ピンク  |
      +----------+----------+
      |cBLK 黒    |cYEL 黄色   |
      \----------+----------/

      /-----------------\
      | Things to do    |
      | cGRE            |
      | o Cut the grass |
      | o Buy jam       |
      | o Fix car       |
      | o Make website  |
      \-----------------/

....

==== PlantUMLで記述するダイアグラム

UMLを記述する場合はPlantUMLがおすすめ。 +
多彩なUMLを気軽に記述できる。


[plantuml, diagram-classes, png]
....
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
....

[plantuml, diagram-sequence, svg]
....
actor Bob #red
' The only difference between actor
'and participant is the drawing
participant Alice
participant "I have a really\nlong name" as L #99FF99
/' You can also declare:
   participant L as "I have a really\nlong name"  #99FF99
  '/

Alice->Bob: Authentication Request
Bob->Alice: Authentication Response
note over Alice, Bob #FFAAAA: This is displayed\n over Bob and Alice.
note over Alice: ノートだよ
Bob->L: Log transaction
Alice->Alice: This is a signal to self.\nIt also demonstrates\nmultiline \ntext
....

==== Syntraxで記述するダイアグラム

[syntrax, diagram-syntrax, svg]
....
indentstack(10,
  line(opt('-'), choice('0', line('1-9', loop(None, '0-9'))),
    opt('.', loop('0-9', None))),

  line(opt(choice('e', 'E'), choice(None, '+', '-'), loop('0-9', None)))
)
....

==== Vegaで記述するダイアグラム

[syntrax, diagram-vega, svg]
....
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "width": 900,
  "height": 560,
  "padding": {"top": 25, "left": 0, "right": 0, "bottom": 0},
  "autosize": "none",

  "signals": [
    {
      "name": "hover",
      "value": null,
      "on": [
        {"events": "@cell:mouseover", "update": "datum"},
        {"events": "@cell:mouseout", "update": "null"}
      ]
    },
    {
      "name": "title",
      "value": "U.S. Airports, 2008",
      "update": "hover ? hover.name + ' (' + hover.iata + ')' : 'U.S. Airports, 2008'"
    },
    {
      "name": "cell_stroke",
      "value": null,
      "on": [
        {"events": "dblclick", "update": "cell_stroke ? null : 'brown'"},
        {"events": "mousedown!", "update": "cell_stroke"}
      ]
    }
  ],

  "data": [
    {
      "name": "states",
      "url": "data/us-10m.json",
      "format": {"type": "topojson", "feature": "states"},
      "transform": [
        {
          "type": "geopath",
          "projection": "projection"
        }
      ]
    },
    {
      "name": "traffic",
      "url": "data/flights-airport.csv",
      "format": {"type": "csv", "parse": "auto"},
      "transform": [
        {
          "type": "aggregate",
          "groupby": ["origin"],
          "fields": ["count"], "ops": ["sum"], "as": ["flights"]
        }
      ]
    },
    {
      "name": "airports",
      "url": "data/airports.csv",
      "format": {"type": "csv", "parse": "auto"},
      "transform": [
        {
          "type": "lookup",
          "from": "traffic", "key": "origin",
          "fields": ["iata"], "as": ["traffic"]
        },
        {
          "type": "filter",
          "expr": "datum.traffic != null"
        },
        {
          "type": "geopoint",
          "projection": "projection",
          "fields": ["longitude", "latitude"]
        },
        {
          "type": "filter",
          "expr": "datum.x != null && datum.y != null"
        },
        {
          "type": "voronoi", "x": "x", "y": "y"
        },
        {
          "type": "collect", "sort": {
            "field": "traffic.flights",
            "order": "descending"
          }
        }
      ]
    },
    {
      "name": "routes",
      "url": "data/flights-airport.csv",
      "format": {"type": "csv", "parse": "auto"},
      "transform": [
        {
          "type": "filter",
          "expr": "hover && hover.iata == datum.origin"
        },
        {
          "type": "lookup",
          "from": "airports", "key": "iata",
          "fields": ["origin", "destination"], "as": ["source", "target"]
        },
        {
          "type": "filter",
          "expr": "datum.source && datum.target"
        },
        {
          "type": "linkpath",
          "shape": "line"
        }
      ]
    }
  ],

  "projections": [
    {
      "name": "projection",
      "type": "albersUsa",
      "scale": 1200,
      "translate": [{"signal": "width / 2"}, {"signal": "height / 2"}]
    }
  ],

  "scales": [
    {
      "name": "size",
      "type": "linear",
      "domain": {"data": "traffic", "field": "flights"},
      "range": [16, 1000]
    }
  ],

  "marks": [
    {
      "type": "path",
      "from": {"data": "states"},
      "encode": {
        "enter": {
          "fill": {"value": "#dedede"},
          "stroke": {"value": "white"}
        },
        "update": {
          "path": {"field": "path"}
        }
      }
    },
    {
      "type": "symbol",
      "from": {"data": "airports"},
      "encode": {
        "enter": {
          "size": {"scale": "size", "field": "traffic.flights"},
          "fill": {"value": "steelblue"},
          "fillOpacity": {"value": 0.8},
          "stroke": {"value": "white"},
          "strokeWidth": {"value": 1.5}
        },
        "update": {
          "x": {"field": "x"},
          "y": {"field": "y"}
        }
      }
    },
    {
      "type": "path",
      "name": "cell",
      "from": {"data": "airports"},
      "encode": {
        "enter": {
          "fill": {"value": "transparent"},
          "strokeWidth": {"value": 0.35}
        },
        "update": {
          "path": {"field": "path"},
          "stroke": {"signal": "cell_stroke"}
        }
      }
    },
    {
      "type": "path",
      "interactive": false,
      "from": {"data": "routes"},
      "encode": {
        "enter": {
          "path": {"field": "path"},
          "stroke": {"value": "black"},
          "strokeOpacity": {"value": 0.35}
        }
      }
    },
    {
      "type": "text",
      "interactive": false,
      "encode": {
        "enter": {
          "x": {"signal": "width", "offset": -5},
          "y": {"value": 0},
          "fill": {"value": "black"},
          "fontSize": {"value": 20},
          "align": {"value": "right"}
        },
        "update": {
          "text": {"signal": "title"}
        }
      }
    }
  ]
}
....
