ドキュメントの記述方法のサンプルです。

=== 記述方法

本ドキュメントはasciidoc形式で記述します。 +
記載方法の詳細は以下のリンクを参照して記載をお願いします。 +
link:https://takumon.github.io/asciidoc-syntax-quick-reference-japanese-translation/[Asciidoctor 文法クイックリファレンス(日本語訳)]

==== 記述時の注意事項

===== セクションタイトルのレベルについて

asciidocはヘッダー(見出し)の扱いが厳格な文書形式です。 +
また多くの人が同時に修正しやすくGitでのマージ等が低コストで行えるように、
レベル1のヘッダーごとにインクルードによるファイルの分割を行ってください。 +
また、分割したファイルではレベル2以降のヘッダーを利用し文書の構造化に努めてください。

=== 注釈等

NOTE: ノート

TIP: ティップス

IMPORTANT: 重要事項

WARNING: 警告

CAUTION: 注意

=== インクルード

.index.adoc
====
これはindex.adocのサンプルです。
[listing]
....
  = サンプルドキュメント (レベル0)
  [[README]]
  == 本ドキュメントについて (レベル1)
  include::README.adoc[]
....
====


.README.adoc
====
これはREADME.adocのサンプルです。
[listing]
....
  === 方針(レベル2)
  本ドキュメントはAsciidocのビルドサンプルとして利用します。
....
====

=== リスト

順序無しリストのネスト

* レベル１
** レベル２
*** レベル３

==== チェックリスト

- [*] チェック済みの要素
- [x] これもチェック済みの要素
- [ ] 未チェックの要素

=== 改ページ

<<<
==== 改ページ後


=== コメントアウト

==== インライン
//はコメントアウトになり出力されません。

==== ブロック
////
ここにコメント
////

=== ラベル



第一項:: 第一項の定義
第二項:: 第二項の定義

=== 水平罫線

'''

=== 表の書き方

.表の書き方
|===
|カラム名 1 |カラム名 2 |カラム名 3

|カラム 1, 行 1 のセル
|カラム 2, 行 1 のセル
|カラム 3, 行 1 のセル

|カラム 1, 行 2 のセル
|カラム 2, 行 2 のセル
|カラム 3, 行 2 のセル
|===


=== ダイアグラム

[ditaa, diagram-sample, png]
....
                   +-------------+
                   | Asciidoctor |-------+
                   |   diagram   |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        | --+ Asciidoctor +--> |               |
 |  Text  |   +-------------+    |   Beautiful   |
 |Document|   |   !magic!   |    |    Output     |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
....

[ditaa, diagram-format, svg]
....

          +-----+
          |{d}  |
          |     |
          |     |
          +-----+

          +-----+
          |{s}  |
          |     |
          |     |
          +-----+

          +-----+
          |{io} |
          |     |
          |     |
          +-----+

          Color codes
      /-------------+------------\
      |cRED  赤     |cBLU  青     |
      +-------------+------------+
      |cGRE  緑     |cPNK  ピンク  |
      +-------------+------------+
      |cBLK  黒     |cYEL  黄色    |
      \-------------+------------/

      /-----------------\
      | Things to do    |
      | cGRE            |
      | o Cut the grass |
      | o Buy jam       |
      | o Fix car       |
      | o Make website  |
      \-----------------/

....

[plantuml, diagram-classes, png]
....
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
....

[plantuml, diagram-sequence, svg]
....
actor Bob #red
' The only difference between actor
'and participant is the drawing
participant Alice
participant "I have a really\nlong name" as L #99FF99
/' You can also declare:
   participant L as "I have a really\nlong name"  #99FF99
  '/

Alice->Bob: Authentication Request
Bob->Alice: Authentication Response
note over Alice, Bob #FFAAAA: This is displayed\n over Bob and Alice.
Bob->L: Log transaction
Alice->Alice: This is a signal to self.\nIt also demonstrates\nmultiline \ntext
....
