name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, closed] #reopened はsynchronizeも走るので消去  #本ドキュメント固有
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        timeout-minutes: 1
        uses: actions/checkout@v3
      # Make SvgBadges 
      - name: Make SvgBadges 
        timeout-minutes: 1
        run: bash ./contents/images/SvgBadges/maketool/make.sh
      # Search Diacritical mark NFD 
      # Unicode正規化がNFDで行われ、濁点・半濁点が親となる文字と分離した場合にwarningを出力
      - name: Search Diacritical mark NFD
        timeout-minutes: 1
        run: bash ./customs/common/utils/search-diacritical-mark-NFD.sh
      # Copy html assets
      - name: Copy html assets
        timeout-minutes: 1
        run: bash ./customs/html/utils/copy-html-assets.sh
      # Make PDF revision NO.
      - name: Make PDF revision NO.
        timeout-minutes: 1
        run: bash ./customs/pdf/images/title/maketool/revnumber.sh
      # Output command using asciidoctor-action
      - name: Convert AsciiDoc step
        id: documents
        timeout-minutes: 3
        uses: Analog-inc/asciidoctor-action@v1
        with:
          shellcommand: "./.github/workflows/asciidoc.sh"
      # Use the output from the documents step
      - name: Save AsciiDoc step
        timeout-minutes: 1
        uses: actions/upload-artifact@v3
        with:
          name: Output-document
          path: ./public/
          retention-days: 1
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_CLIFF_056900F00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./public" # App source code path  #本ドキュメント固有
          api_location: "./customs/azureFunctions/api" # Api source code path - optional  #本ドキュメント固有
          output_location: "" # Built app content directory - optional
          routes_location: "./customs/azureFunctions"   #本ドキュメント固有
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_CLIFF_056900F00 }}
          action: "close"
