name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, closed] #reopened はsynchronizeも走るので消去  #本ドキュメント固有
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true
      # Output command using asciidoctor-action #本ドキュメント固有
      - name: Build AsciiDoc step
        id: documents
        uses: Analog-inc/asciidoctor-action@v1
        with:
          shellcommand: "./.github/workflows/asciidoc.sh"
      # Use the output from the documents step  #本ドキュメント固有
      - name: Save AsciiDoc step
        if: ${{ contains(github.ref, 'output/') }}
        uses: actions/upload-artifact@v1
        with:
          name: Output-document
          path: ./outputs/
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_CLIFF_056900F00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./outputs" # App source code path  #本ドキュメント固有
          api_location: "./azureFunctions/api" # Api source code path - optional  #本ドキュメント固有
          output_location: "" # Built app content directory - optional
          routes_location: "./azureFunctions"   #本ドキュメント固有
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_CLIFF_056900F00 }}
          action: "close"
